FORMAT: 1A
HOST: https://bethro.alwaysdata.net/api/v1

# suplike

simply work with suplike social website.

## Questions Collection [/signup]

### Signup a new user [POST]

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "question": "Favourite programming language?",
        }

+ Response 200 (application/json)

        [
        ]


## Questions Collection [/login]

### Login to an existing account [POST]

this enebles you to login to suplike using an existing account.
Please note that you are required to store the information and use it to send later requests.

 + Request (application/json)

        {
            "usermail": "username", // can also be email
            "userpass": "password"  // the users password
        }

 + Response 201 (application/json)

    + Headers

            Location: /login

    + Body

            {
               "username": "test",
               "profile_picture": "http://localhost/suplike/img/download.jpg",
               "full_name": "fname lname",
               "user_token": "fb787eb1d2a7b234866b912b8e14191260b8f3e5fb2dc6ea53a53104ee",
               "chat_key": "3e1630d6e3e"
            }
     
## Questions Collection [/post]
 
### this is for getting posts [GET]